name: Run Colab Notebook

on:
  schedule:
    - cron: "*/2 * * * *"

jobs:
  run_colab:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2   # 更新到支援 node16 的版本
      with:
        ref: v2   # 更新為操作的新版本號

    - name: Set up Python
      uses: actions/setup-python@v2   # 更新到支援 node16 的版本
      with:
        python-version: 3.7

    - name: Install required packages
      run: |
        pip install jupyter nbconvert yfinance gspread requests

    - name: Run Colab notebook
      run: |
        jupyter nbconvert --execute HSI.py



